alias v="nvim"
alias cl="clear"

alias so="source "

alias config="cd ~/.config && ls"
alias i3conf="nvim ~/.config/i3/config"
alias vconf="nvim ~/.config/nvim/init.vim"
alias fishconf="nvim ~/.config/fish/config.fish"
alias alacconf="nvim ~/.config/alacritty/alacritty.yml"
alias tmuxconf="nvim ~/.tmux.conf"

alias g ="git "
alias gs="git status -sb"
alias gaa="git add -A"
alias gcmsg="git commit -m "
alias gb="git branch"
alias gd="git diff"
alias gpush="git push"
alias gpull="git pull"
alias grim="git rebase -i master"

alias lsd="ls -d .*"
alias la="ls -a"

alias ..="cd .. && ls"
alias ...="cd ../.. && ls"
alias dots="nvim ~/Code/DotFiles/"
alias cdcd="cd ~/Code/ && ls"
alias cdpy="cd ~/Code/Python && ls"
alias cdja="cd ~/Code/Java && ls"
alias cdjs="cd ~/Code/Javascript && ls"
alias cdts="cd ~/Code/TypeScript && ls"
alias cdrs="cd ~/Code/Rust && ls"
alias cdcpp="cd ~/Code/C++ && ls"
alias cdbs="cd ~/Code/Scripts && ls"
alias cddf="cd ~/Code/DotFiles && ls"
alias cdcc="cd ~/Code/Code_Challenges && ls"
alias cddl="cd ~/Downloads && ls"

