# Place/Link in ~/.config/starship.toml
# Change default configuration file location with STARSHIP_CONFIG environment variable :
#	export STARSHIP_CONFIG=~/.starship/config.toml
# By default starship logs warnings and errors into a file named ~/.cache/starship




# Inserts a blank line between shell prompts
add_newline = true


# Replace the ">" symbol in the prompt with better arrow
[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red) "



