#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi


if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi


if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi


if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi




if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

xrandr --output DisplayPort-2 --mode 3440x1440 --rate 100.00 --primary --pos 0x0 --rotate normal --output HDMI-A-0 --mode 1920x1080  --rate 120.00 --pos 750x-1425 --rotate normal

#~/.fehbg &
if [ -e ~/.Xresources ] || [ -L ~/.Xresources ]
then
	xrdb -merge ~/.Xresources
fi

exec i3
export _JAVA_AWT_WM_NONREPARENTING=1
