# Self contained zsh configs located in ~/.config/zsh/*
ZDOTDIR=$HOME/.config/zsh
source -- "$ZDOTDIR"/zshenv
. "$HOME/.cargo/env"

if [ -e /home/prometheus/.nix-profile/etc/profile.d/nix.sh ]; then . /home/prometheus/.nix-profile/etc/profile.d/nix.sh; fi # added by Nix installer
