alias v="nvim"
alias cl="clear"
alias chmox="chmod +x"
alias echopath="echo '$PATH' | tr ':' '\n' | nl"

alias so="source "

alias todo="nvim ~/Documents/todo.md"

alias config="cd ~/.config"
alias i3conf="nvim ~/.config/i3/config"
alias vconf="nvim ~/.config/nvim/init.vim"
alias fishconf="nvim ~/.config/fish/config.fish"
alias alacconf="nvim ~/.config/alacritty/alacritty.yml"
alias tmuxconf="nvim ~/.tmux.conf"
alias iscript="cd ~/Code/Scripts/ProjectScripts/OS_Install_Script"

alias nvdir="cd ~/Code/DotFiles/Nvim-Config"

alias g ="git "
alias gs="git status -sb"
alias gaa="git add -A"
alias gcmsg="git commit -m "
alias gb="git branch"
alias gd="git diff"
alias gpush="git push"
alias gpull="git pull"
alias grim="git rebase -i master"

alias lsd="ls -d .*"
alias la="ls -a"

alias ..="cd .."
alias ...="cd ../.."
alias dots="nvim ~/Code/DotFiles/"
alias cdcd="cd ~/Code/"
alias cdpy="cd ~/Code/Python"
alias cdja="cd ~/Code/Java"
alias cdjs="cd ~/Code/Javascript"
alias cdts="cd ~/Code/TypeScript"
alias cdrs="cd ~/Code/Rust"
alias cdcpp="cd ~/Code/C++"
alias cdbs="cd ~/Code/Scripts"
alias cddf="cd ~/Code/DotFiles"
alias cdcc="cd ~/Code/Code_Challenges"
alias cddl="cd ~/Downloads"
alias cdms="cd ~/Code/Misc"

alias intellij="intellij-idea-community"
alias dev="~/Code/DotFiles/dev-tmux.sh"

alias pwroff="shutdown now"
alias pwrcl="shutdown -c"
alias reboot="shutdown -r"
